version: 1.0.{build}
clone_depth: 1
environment:
  nodejs_version: 8
platform:
  - x64
configuration:
  - Release
init:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- ps: Install-Product node $env:nodejs_version x64
- set EDGE_USE_CORECLR= && yarn install
cache: '%LOCALAPPDATA%\Yarn'
build_script:
- cmd: >-
    yarn run ci
test_script:
- cmd: >-
    yarn run test
artifacts:
- path: dist\Vortex Setup *.exe
  name: Setup
on_failure:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
