name: Nightly Build

on:
  schedule:
    - cron: "0 19 * * *" # Nightly at 19:00 UTC
  workflow_dispatch:

permissions:
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'package.yml',
              ref: 'master',
              inputs: {
                nightly: 'true'
              }
            })
