name: Test SDK

on:
  workflow_dispatch:

jobs:
  test-sdk:
    runs-on: windows-latest

    steps:
      - name: Show Windows version
        run: |
          Write-Host "OS version:"
          [System.Environment]::OSVersion.VersionString
          Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer
        shell: pwsh

      - name: List all Windows SDK versions
        run: |
          Write-Host "=== Windows SDKs from File Path ===" -ForegroundColor Cyan
          $sdks = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\Include" -Directory |
                  Select-Object -ExpandProperty Name
          $sdks | ForEach-Object { Write-Host $_ }
          
          Write-Host "`n=== Windows SDKs from Visual Studio (via vswhere) ===" -ForegroundColor Cyan
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          
          if (Test-Path $vswhere) {
              & $vswhere -products * -requires Microsoft.VisualStudio.Component.Windows10SDK -format json |
                  ConvertFrom-Json | ForEach-Object {
                      $_.packages | Where-Object { $_.id -like "Microsoft.VisualStudio.Component.Windows10SDK*" } |
                      Select-Object -ExpandProperty id
                  } | ForEach-Object { Write-Host $_ }
          } else {
              Write-Host "vswhere.exe not found. Visual Studio may not be installed." -ForegroundColor Yellow
          }
        shell: pwsh
