name: Test Windows 10 SDK Component

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-windows-sdk:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test for Windows 10 SDK 19041
      shell: powershell
      run: |
        $sdkComponent = "Microsoft.VisualStudio.Component.Windows10SDK.19041"
        $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        
        # Check which SDK components are installed
        $sdkPatterns = @(
            "Microsoft.VisualStudio.Component.Windows10SDK.22621",
            "Microsoft.VisualStudio.Component.Windows10SDK.20348", 
            "Microsoft.VisualStudio.Component.Windows10SDK.19041",
            "Microsoft.VisualStudio.Component.Windows10SDK.18362",
            "Microsoft.VisualStudio.Component.Windows11SDK.22000"
        )
        
        Write-Host "Installed Windows SDK components:"
        $componentFound = $false
        foreach ($pattern in $sdkPatterns) {
            $result = & $vswherePath -latest -products * -requires $pattern -format json
            if ($result -and $result.Trim() -ne "" -and $result -ne "[]") {
                Write-Host "FOUND: $pattern"
                if ($pattern -eq $sdkComponent) {
                    $componentFound = $true
                }
            }
        }
        
        Write-Host "Target component $sdkComponent available: $componentFound"
        echo "SDK_AVAILABLE=$componentFound" >> $env:GITHUB_OUTPUT
      id: sdk-check
    
    - name: Install SDK if missing
      if: steps.sdk-check.outputs.SDK_AVAILABLE == 'false'
      shell: powershell
      run: |
        Write-Host "Installing $sdkComponent"
        # Add installation command here
